# Generated by Django 2.2.7 on 2019-11-18 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('url_slug', models.CharField(max_length=50, unique=True)),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('likes', models.IntegerField(default=1)),
                ('content', models.TextField()),
                ('feature_img_url', models.CharField(blank=True, max_length=500, null=True)),
                ('categories', models.ManyToManyField(related_name='blog_posts', to='webapp.Category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='blog_posts', to='webapp.Tag')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
